### ISSUE TITLE
About the OpenCv installation

### ISSUE THREAD

**Issue by simaybocu** [yushulx/mrz4nodejs#1]
I am using iMac and https://github.com/yushulx/mrz4nodejs/tree/main/examples when I download OpenCV from https://opencv.org/releases/ to run the sample code here  it gives error like this: 
![1666874573074](https://user-images.githubusercontent.com/33957028/198289242-a801bbed-488f-4a44-8429-484d9501a623.jpg)

I guess I can't install opencv4nodejs because it's not :(
Can you help me, please, where I'm wrong?

**Comment by yushulx** [comment]
@simaybocu the package is built with native C/C++ libraries. Mac is not supported.

![image](https://user-images.githubusercontent.com/2202306/198434428-1d529a6c-69d4-4c0a-8932-43be156664fb.png)
